## https://docs.anaconda.com/anaconda-cloud/user-guide/tutorials/
package:
  name: lisa
  version: 1.0

build:
  number: 6
  #entry_points:
  #  - lisa = ../bin/lisa

requirements:
  build:
    - python
    - fire
    - setuptools
    - numpy ==1.15.1
    - patchelf
    - {{ compiler('c') }}
  host:
    - python
    - zlib
    - numpy ==1.15.1
  run:
    - python
    - zlib
    - mkl-service
    - curl
    - fire
    - scikit-learn
    - theano
    - pandas
    - h5py
    - PyYAML >=3.12
    - snakemake
    - yappi
    - bwa
    - samtools=0.1.19 
    - bedtools=2.17.0 
    - seqtk 
    - ucsc-bedclip 
    - ucsc-bedgraphtobigwig 
    - ucsc-wigcorrelate 
    - ucsc-wigtobigwig
    - deeptools
    - openssl=1.0
    - mpmath

    #- matplotlib
    #- seaborn

about:
  home: http://lisa.cistrome.org
  license: EULA
  license_family: OTHER
  license_file: ../LICENSE
  summary: 'ChIP-seq/DNase-seq data-driven TF and CR prioritization tool'
