{% set data = load_setup_py_data() %}
package:
  name: lisa
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/qinqian/lisa

build:
  number: 1
  entry_points:
    - lisa = ../bin/lisa

requirements:
  build:
    - python
    - setuptools
    - gcc
    - numpy
  run:
    - python
    - numpy
    - theano
    - scipy
    - fire
    - h5py
    - sklearn
    - pandas
    - yappi
    - snakemake
    - matplotlib
    - seaborn
    - PyYAML >=3.12

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_family: OTHER
  license_file: LICENSE
  summary: {{ data.get('description') }}
